# Generated by Django 4.1.5 on 2023-04-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_remove_users_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ward',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
