# Generated by Django 4.1.5 on 2023-05-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
