# Generated by Django 4.1.5 on 2023-03-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img_path', models.ImageField(null=True, upload_to='Notification')),
                ('desc', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.member')),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('voter_id', models.CharField(max_length=20, unique=True)),
                ('job', models.CharField(max_length=20)),
                ('tax_payer', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('blood_group', models.CharField(max_length=3)),
                ('date_of_birth', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('img_path', models.ImageField(null=True, upload_to='Complaints')),
                ('status', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('update_on', models.DateField(auto_now=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.member')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.users')),
            ],
        ),
    ]
