# Generated by Django 4.1.5 on 2023-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_family_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='img_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='img_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
