# Generated by Django 4.1.5 on 2023-04-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_comp_img_path_alter_notification_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='remark',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=20)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.comp')),
            ],
        ),
    ]
