# Generated by Django 4.1.5 on 2023-04-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_remove_comp_remark_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='age',
            field=models.IntegerField(),
        ),
    ]
